<script setup>
import { onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { api } from '../lib/api'
const route = useRoute(); const outline = ref(null); const loading = ref(true); const error = ref('')
const load = async () => { loading.value = true; error.value = ''; try { outline.value = await api(route.meta.privatePreview ? `/api/me/collections/${route.params.id}/preview` : `/api/collections/${route.params.id}/outline`) } catch (e) { error.value = e.message } finally { loading.value = false } }
onMounted(load); watch(() => route.fullPath, load)
const formatLabel = (value) => ({ GUIDE: '步骤指南', READING_PATH: '阅读路线', RESOURCE_LIST: '资源清单', CUSTOM: '自由专题' }[value] || value)
</script>
<template>
  <div v-if="loading" class="loading standalone-loading">正在加载专题…</div><section v-else-if="outline" class="page-hero collection-reading-hero"><p v-if="route.meta.privatePreview" class="preview-banner">私人阅读预览 · 仅自己可见 <RouterLink :to="`/me/collections/${route.params.id}/edit`">继续编辑 →</RouterLink></p><span class="kicker">{{ formatLabel(outline.collection.format) }}</span><h1>{{ outline.collection.name }}</h1><p>{{ outline.collection.description }}</p><div v-if="outline.collection.audience || outline.collection.goal" class="reading-goals"><p v-if="outline.collection.audience"><strong>适合谁</strong>{{ outline.collection.audience }}</p><p v-if="outline.collection.goal"><strong>完成目标</strong>{{ outline.collection.goal }}</p></div><div class="collection-detail-meta"><span>{{ outline.collection.ownerName }} 创建</span><span>{{ outline.sections.length }} 个章节</span></div></section><section v-if="outline" class="section reading-section"><div class="reading-layout"><nav class="outline-nav" aria-label="专题目录"><span class="kicker">OUTLINE</span><a v-for="(section, index) in outline.sections" :key="section.id" :href="`#section-${section.id}`"><small>{{ String(index + 1).padStart(2, '0') }}</small>{{ section.title }}</a></nav><main class="reading-content"><article v-for="(section, index) in outline.sections" :id="`section-${section.id}`" :key="section.id" class="reading-chapter"><header><span>{{ String(index + 1).padStart(2, '0') }}</span><div><h2>{{ section.title }}</h2><p v-if="section.description">{{ section.description }}</p></div></header><div v-if="!section.entries.length" class="empty-state">本章暂时没有内容。</div><div v-for="entry in section.entries" :key="entry.id" class="reading-entry" :class="`entry-${entry.kind.toLowerCase()}`"><span class="post-tag">{{ { NOTE: '笔记', POST: '站内内容', LINK: '外部链接' }[entry.kind] }}</span><template v-if="entry.kind === 'NOTE'"><h3 v-if="entry.title">{{ entry.title }}</h3><p class="entry-body">{{ entry.body }}</p></template><template v-else-if="entry.kind === 'POST'"><RouterLink v-if="entry.postId" :to="{ path: '/', query: { post: entry.postId } }"><h3>{{ entry.postTitle }}</h3><p>{{ entry.postSummary }}</p><small>{{ entry.postAuthor }}</small></RouterLink><p v-else>原文已不可用</p></template><template v-else><a v-if="entry.externalUrl" :href="entry.externalUrl" target="_blank" rel="noopener noreferrer"><h3>{{ entry.title }} ↗</h3></a><p v-else>链接尚未填写</p></template><p v-if="entry.annotation" class="entry-annotation">{{ entry.annotation }}</p></div></article></main></div></section><section v-else-if="!loading" class="section"><div class="empty-state"><p>{{ error }}</p><RouterLink to="/collections">返回专题广场 →</RouterLink></div></section>
</template>
