create table user_accounts (
    id bigint generated by default as identity primary key,
    email varchar(120) not null,
    password_hash varchar(100) not null,
    display_name varchar(40) not null,
    created_at timestamp with time zone not null
);
create unique index uq_user_accounts_email_ci on user_accounts (lower(email));

create table content_posts (
    id bigint generated by default as identity primary key,
    type varchar(12) not null check (type in ('ARTICLE', 'TOPIC')),
    title varchar(120) not null,
    summary varchar(280) not null,
    body text not null,
    author_id bigint not null references user_accounts(id),
    author_name varchar(40) not null,
    created_at timestamp with time zone not null,
    likes integer not null default 0 check (likes >= 0)
);
create index idx_post_type_created on content_posts(type, created_at desc, id desc);

create table comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references content_posts(id) on delete cascade,
    author_id bigint not null references user_accounts(id),
    author_name varchar(40) not null,
    body varchar(1000) not null,
    created_at timestamp with time zone not null
);
create index idx_comment_post_created on comments(post_id, created_at, id);

create table community_collections (
    id bigint generated by default as identity primary key,
    name varchar(80) not null,
    description varchar(260) not null,
    owner_name varchar(40) not null,
    item_count integer not null default 0 check (item_count >= 0),
    created_at timestamp with time zone not null
);
create index idx_collection_created on community_collections(created_at desc, id desc);

create table vps_recommendations (
    id bigint generated by default as identity primary key,
    provider varchar(60) not null,
    plan_name varchar(80) not null,
    region varchar(50) not null,
    cpu integer not null,
    memory_gb integer not null,
    storage_gb integer not null,
    monthly_price numeric(10,2) not null,
    score double precision not null,
    description varchar(300) not null,
    author_name varchar(40) not null,
    created_at timestamp with time zone not null
);

