alter table user_accounts add column bio varchar(500) not null default '';

alter table community_collections add column owner_id bigint references user_accounts(id) on delete set null;
alter table community_collections add column updated_at timestamp with time zone not null default current_timestamp;
create index idx_collection_owner_updated on community_collections(owner_id, updated_at desc, id desc);

create table collection_posts (
    id bigint generated by default as identity primary key,
    collection_id bigint not null references community_collections(id) on delete cascade,
    post_id bigint not null references content_posts(id) on delete cascade,
    created_at timestamp with time zone not null,
    constraint uq_collection_post unique(collection_id, post_id)
);
create index idx_collection_posts_post on collection_posts(post_id, collection_id);

create table user_collection_preferences (
    user_id bigint primary key references user_accounts(id) on delete cascade,
    version bigint not null default 0,
    updated_at timestamp with time zone not null default current_timestamp
);

create table user_collection_selections (
    id bigint generated by default as identity primary key,
    user_id bigint not null references user_accounts(id) on delete cascade,
    collection_id bigint not null references community_collections(id) on delete cascade,
    sort_order integer not null check (sort_order >= 0),
    created_at timestamp with time zone not null,
    constraint uq_user_collection_selection unique(user_id, collection_id),
    constraint uq_user_collection_order unique(user_id, sort_order)
);
