alter table community_collections add column format varchar(24) not null default 'CUSTOM';
alter table community_collections add column status varchar(16) not null default 'PUBLISHED';
alter table community_collections add column audience varchar(160) not null default '';
alter table community_collections add column goal varchar(300) not null default '';
alter table community_collections add column revision bigint not null default 0;
alter table community_collections add column published_at timestamp with time zone;

alter table community_collections add constraint ck_collection_format
    check (format in ('GUIDE','READING_PATH','RESOURCE_LIST','CUSTOM'));
alter table community_collections add constraint ck_collection_status
    check (status in ('DRAFT','PUBLISHED','ARCHIVED'));
alter table community_collections add constraint ck_collection_revision check (revision >= 0);

update community_collections set published_at=coalesce(updated_at,created_at) where status='PUBLISHED';

create table collection_sections (
    id bigint generated by default as identity primary key,
    collection_id bigint not null references community_collections(id) on delete cascade,
    title varchar(80) not null,
    description varchar(500) not null default '',
    sort_order integer not null check (sort_order >= 0),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint uq_collection_section_order unique(collection_id,sort_order),
    constraint uq_collection_section_identity unique(id,collection_id)
);

create table collection_entries (
    id bigint generated by default as identity primary key,
    collection_id bigint not null references community_collections(id) on delete cascade,
    section_id bigint not null,
    kind varchar(12) not null check (kind in ('NOTE','POST','LINK')),
    sort_order integer not null check (sort_order >= 0),
    title varchar(160),
    annotation varchar(1000) not null default '',
    body text,
    post_id bigint references content_posts(id) on delete set null,
    external_url varchar(2000),
    created_at timestamp with time zone not null default current_timestamp,
    updated_at timestamp with time zone not null default current_timestamp,
    constraint fk_collection_entry_section foreign key(section_id,collection_id)
        references collection_sections(id,collection_id) on delete cascade,
    constraint uq_collection_entry_order unique(section_id,sort_order),
    constraint uq_collection_entry_post unique(collection_id,post_id),
    constraint ck_collection_entry_payload check (
        (kind='NOTE' and body is not null and post_id is null and external_url is null) or
        (kind='POST' and post_id is not null and body is null and external_url is null) or
        (kind='LINK' and title is not null and external_url is not null and post_id is null and body is null)
    )
);

create index idx_collection_status_updated on community_collections(status,updated_at desc,id desc);
create index idx_collection_section_collection on collection_sections(collection_id,sort_order,id);
create index idx_collection_entry_collection on collection_entries(collection_id,section_id,sort_order,id);
create index idx_collection_entry_post on collection_entries(post_id,collection_id);

insert into collection_sections(collection_id,title,description,sort_order,created_at,updated_at)
select id,'专题内容','',0,created_at,updated_at from community_collections;

insert into collection_entries(collection_id,section_id,kind,sort_order,title,annotation,body,post_id,external_url,created_at,updated_at)
select cp.collection_id,s.id,'POST',
       cast(row_number() over(partition by cp.collection_id order by cp.created_at desc,cp.post_id desc)-1 as integer),
       null,'',null,cp.post_id,null,cp.created_at,cp.created_at
from collection_posts cp
join collection_sections s on s.collection_id=cp.collection_id and s.sort_order=0;
